#!/usr/bin/env bash
# Tests scripts/gh/resolve-generated.sh on throwaway repositories built here.
#
# The tool exists because a conflict inside a GENERATED block is not a decision:
# both sides are stale copies of something a program emits, and the merged tree
# has a third answer that neither branch ever saw. Case `inside-the-block` is
# that situation in miniature - two branches each add a file and each rewrites
# the census block to say "2", and the merged tree has three.
#
# Everything here is hermetic: `git init` under a mktemp directory, emitters
# written INSIDE the throwaway repository (never in this one), no network, and
# a trap that removes the lot. The emitters drop a sentinel file the moment they
# start, which is how the security cases prove that a refused path was not
# merely reported - it was not executed.
#
# The last section MUTATES the tool and re-runs the case each mutation should
# break. A battery that has never been shown to go red is a battery whose green
# says nothing.
#
# Exit codes: 0 = every case behaved | 1 = some case did not | 2 = harness broke.
set -uo pipefail

SP="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd -- "$SP/../../.." && pwd)"
TOOL_REL="scripts/gh/resolve-generated.sh"
TOOL="$ROOT/$TOOL_REL"
[ -f "$TOOL" ] || { echo "  COULD NOT MEASURE: $TOOL_REL is missing (rc 2)"; exit 2; }
command -v git     >/dev/null 2>&1 || { echo "  COULD NOT MEASURE: git is missing (rc 2)"; exit 2; }
command -v python3 >/dev/null 2>&1 || { echo "  COULD NOT MEASURE: python3 is missing (rc 2)"; exit 2; }

# Hermetic git: whatever this machine has in ~/.gitconfig must not decide what
# a conflict looks like. `rerere` in particular would resolve the headline case
# from a cache and leave the battery measuring nothing.
export GIT_CONFIG_NOSYSTEM=1
export GIT_CONFIG_GLOBAL=/dev/null

LAB="$(mktemp -d)"; trap 'rm -rf "$LAB"' EXIT
pass=0; fail=0

G() { git -C "$1" -c user.email=t@e -c user.name=t -c rerere.enabled=false \
               -c merge.conflictstyle=merge -c core.autocrlf=false "${@:2}"; }

run_tool() {  # <repo> <tool> [args...] -> prints rc, output lands in $LAB/out.txt
  local d="$1" t="$2"; shift 2
  ( cd "$d" && bash "$t" "$@" >"$LAB/out.txt" 2>&1 ); echo $?
}

res() {  # <label> <got> <want> [needle]
  local label="$1" got="$2" want="$3" needle="${4:-}"
  if [ "$got" = "$want" ] && { [ -z "$needle" ] || grep -qi -- "$needle" "$LAB/out.txt"; }; then
    printf '  PASS  %-56s rc=%s\n' "$label" "$got"; pass=$((pass+1))
  else
    printf '  FAIL  %-56s rc=%s (expected %s)\n' "$label" "$got" "$want"
    sed 's/^/        | /' "$LAB/out.txt" | tail -12; fail=$((fail+1))
  fi
}

# One number for the whole tree, .git excluded. "Nothing was written" is a claim
# about the TREE, not about the one file the case happens to look at, and a
# resolver that fails closed on one file while quietly rewriting another would
# pass a narrower check.
treesum() { ( cd "$1" && find . -path ./.git -prune -o -type f -print | LC_ALL=C sort | xargs cksum | cksum ); }

# ---------------------------------------------------------------------------
# Fixtures: a throwaway repository with a real generated block and real emitters
# ---------------------------------------------------------------------------

# A tiny stand-in for scripts/gates/lib/doc_census.py. It counts the .txt files
# under data/ and rewrites every region whose begin marker names IT - which is
# the property the tool relies on and the reason the tool reads the emitter out
# of the file instead of keeping a list.
emitter() {  # <repo> <repo-relative path> <normal|lazy|flaky|angry>
  local d="$1" rel="$2" mode="$3"
  mkdir -p "$d/$(dirname "$rel")"
  { printf 'SELF = "%s"\nMODE = "%s"\n' "$rel" "$mode"
    cat <<'PY'
import pathlib, re, sys

# The sentinel is written before anything else: it is how the battery proves an
# emitter the tool refused was not merely reported but genuinely never ran.
with open(".emitter-ran", "a") as fh:
    fh.write(SELF + " " + " ".join(sys.argv[1:]) + "\n")

if MODE == "angry":
    sys.stderr.write("this emitter refuses to run\n")
    raise SystemExit(3)

DOC = pathlib.Path("docs/census.md")
WRITE = "--write" in sys.argv[1:]
BEGIN = re.compile(r"<!--\s*([A-Za-z0-9_.-]+):begin \(generated by (\S+)")
END = re.compile(r"<!--\s*([A-Za-z0-9_.-]+):end\s*-->")


def block(tag):
    d = pathlib.Path("data")
    names = sorted(p.name for p in d.glob("*.txt")) if d.is_dir() else []
    return ["<!-- %s:begin (generated by %s - do not edit by hand) -->" % (tag, SELF),
            "- files counted: %d" % len(names),
            "- files: %s" % ", ".join(names),
            "<!-- %s:end -->" % tag]


if not DOC.exists():
    sys.stderr.write("there is no %s to emit into\n" % DOC)
    raise SystemExit(2)

lines = DOC.read_text().split("\n")
out, i, mismatch = [], 0, False
while i < len(lines):
    mb = BEGIN.search(lines[i])
    if mb and mb.group(2) == SELF:
        tag = mb.group(1)
        j = i + 1
        while j < len(lines) and not (END.search(lines[j]) and END.search(lines[j]).group(1) == tag):
            j += 1
        if j >= len(lines):
            sys.stderr.write("the %s block is never closed\n" % tag)
            raise SystemExit(2)
        cur, new = lines[i:j + 1], block(tag)
        if cur != new:
            mismatch = True
        out.extend(cur if MODE == "lazy" else new)
        i = j + 1
        continue
    out.append(lines[i])
    i += 1

if WRITE:
    DOC.write_text("\n".join(out))
    raise SystemExit(0)
if MODE == "lazy":
    raise SystemExit(0)
if MODE == "flaky":
    raise SystemExit(1)
raise SystemExit(1 if mismatch else 0)
PY
  } > "$d/$rel"
}

marker_begin() { printf '<!-- %s:begin (generated by %s - do not edit by hand) -->\n' "$1" "$2"; }
marker_end()   { printf '<!-- %s:end -->\n' "$1"; }

# The tree every hand-built case starts from: three files under data/, so a
# block that claims two is stale and a regeneration really moves it.
build_repo() {  # <dir> [<emitter-path>:<mode> ...]
  local d="$1" spec
  mkdir -p "$d/docs" "$d/data" "$d/tools"
  printf 'one\n' > "$d/data/one.txt"
  printf 'a\n'   > "$d/data/a.txt"
  printf 'b\n'   > "$d/data/b.txt"
  emitter "$d" scripts/gates/lib/fake_census.py normal
  for spec in "${@:2}"; do emitter "$d" "${spec%%:*}" "${spec#*:}"; done
  { printf '# Census of a throwaway repository\n\n'
    printf 'Prose above the block, which nobody generates.\n\n'
    marker_begin census scripts/gates/lib/fake_census.py
    printf -- '- files counted: 3\n- files: a.txt, b.txt, one.txt\n'
    marker_end census
    printf '\nProse below the block, also nobody edits it by hand.\n'
  } > "$d/docs/census.md"
  git -C "$d" init -q -b main
  G "$d" add -A; G "$d" commit -qm base
}

# A conflict BETWEEN the markers: both sides stale, the tree says three.
doc_conflict_inside() {  # <dir> [emitter-path-for-the-marker]
  local d="$1" em="${2:-scripts/gates/lib/fake_census.py}"
  { printf '# Census of a throwaway repository\n\n'
    printf 'Prose above the block, which nobody generates.\n\n'
    marker_begin census "$em"
    printf -- '- files counted: 2\n'
    printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
    marker_end census
    printf '\nProse below the block, also nobody edits it by hand.\n'
  } > "$d/docs/census.md"
}

echo "== resolve-generated.sh on throwaway repositories"

# ---------------------------------------------------------------------------
# a. THE HEADLINE CASE, from a real merge: the conflict is inside the block,
#    both sides say two, and the merged tree has three.
# ---------------------------------------------------------------------------
d="$LAB/a"
mkdir -p "$d/docs" "$d/data"
emitter "$d" scripts/gates/lib/fake_census.py normal
printf 'one\n' > "$d/data/one.txt"
{ printf '# Census of a throwaway repository\n\n'
  printf 'Prose above the block, which nobody generates.\n\n'
  marker_begin census scripts/gates/lib/fake_census.py
  printf -- '- files counted: 1\n- files: one.txt\n'
  marker_end census
  printf '\nProse below the block, also nobody edits it by hand.\n'
} > "$d/docs/census.md"
git -C "$d" init -q -b main; G "$d" add -A; G "$d" commit -qm base
G "$d" checkout -q -b feat/a
printf 'a\n' > "$d/data/a.txt"
( cd "$d" && python3 -- scripts/gates/lib/fake_census.py --write )
G "$d" add -A; G "$d" commit -qm "branch a adds a.txt"
G "$d" checkout -q main; G "$d" checkout -q -b feat/b
printf 'b\n' > "$d/data/b.txt"
( cd "$d" && python3 -- scripts/gates/lib/fake_census.py --write )
G "$d" add -A; G "$d" commit -qm "branch b adds b.txt"
G "$d" checkout -q feat/a
G "$d" merge --no-edit -q feat/b >/dev/null 2>&1
rm -f "$d/.emitter-ran"
unmerged="$(G "$d" diff --name-only --diff-filter=U | tr '\n' ' ')"
res "the fixture really is an unmerged tree" "$unmerged" "docs/census.md "
res "a. conflict inside the block, no PATH given -> rc 0" "$(run_tool "$d" "$TOOL")" 0 "regenerated"
res "a. and it says both sides were stale" "$(grep -c 'BOTH sides were stale' "$LAB/out.txt")" 1
res "a. no conflict marker survives" \
    "$(grep -c -e '^<<<<<<< ' -e '^=======$' -e '^>>>>>>> ' "$d/docs/census.md")" 0
res "a. the block says what the tree says, not what a branch said" \
    "$(grep -c '^- files counted: 3$' "$d/docs/census.md")" 1
res "a. and the emitter's own check mode agrees" \
    "$( cd "$d" && python3 -- scripts/gates/lib/fake_census.py >/dev/null 2>&1; echo $? )" 0

# ---------------------------------------------------------------------------
# b. a conflict OUTSIDE any generated region is a person's decision
# ---------------------------------------------------------------------------
d="$LAB/b"; build_repo "$d"
{ printf '# Census of a throwaway repository\n\n'
  marker_begin census scripts/gates/lib/fake_census.py
  printf -- '- files counted: 3\n- files: a.txt, b.txt, one.txt\n'
  marker_end census
  printf '\n<<<<<<< HEAD\nProse one branch wrote.\n=======\nProse the other wrote.\n>>>>>>> feat/b\n'
} > "$d/docs/census.md"
before="$(treesum "$d")"
res "b. conflict outside every region -> rc 1" "$(run_tool "$d" "$TOOL" docs/census.md)" 1 "not inside any generated region"
res "b. and it names the lines" "$(grep -c 'lines 8-12' "$LAB/out.txt")" 1
res "b. and the tree is byte-identical" "$(treesum "$d")" "$before"

# ---------------------------------------------------------------------------
# c. FAIL CLOSED: one hunk in, one hunk out -> nothing at all is written
# ---------------------------------------------------------------------------
d="$LAB/c"; build_repo "$d"
{ printf '# Census of a throwaway repository\n\n'
  marker_begin census scripts/gates/lib/fake_census.py
  printf -- '- files counted: 2\n'
  printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
  marker_end census
  printf '\n<<<<<<< HEAD\nProse one branch wrote.\n=======\nProse the other wrote.\n>>>>>>> feat/b\n'
} > "$d/docs/census.md"
before="$(treesum "$d")"
res "c. one hunk in, one hunk out -> rc 1" "$(run_tool "$d" "$TOOL" docs/census.md)" 1 "NOTHING has been written"
res "c. the generated hunk was NOT resolved either" "$(treesum "$d")" "$before"
res "c. and the emitter never ran" "$([ -e "$d/.emitter-ran" ] && echo present || echo absent)" absent

# ---------------------------------------------------------------------------
# d. the marker names an emitter that is not in the tree
# ---------------------------------------------------------------------------
d="$LAB/d"; build_repo "$d"
doc_conflict_inside "$d" scripts/gates/lib/ghost_census.py
before="$(treesum "$d")"
res "d. marker names an emitter nobody tracks -> rc 2" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "git does not track it"
res "d. and nothing was written" "$(treesum "$d")" "$before"

# d2. the same, mixed with a region whose emitter IS fine. One bad emitter must
#     stop the WHOLE run, or the good half lands and the bad half silently keeps
#     one branch's stale figures. This is the case mutant m4 is measured against.
d="$LAB/d2"; build_repo "$d"
{ printf '# Two blocks, one emitter missing\n\n'
  marker_begin census scripts/gates/lib/fake_census.py
  printf -- '- files counted: 2\n'
  printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
  marker_end census
  printf '\n'
  marker_begin ghost scripts/gates/lib/ghost_census.py
  printf -- '- files counted: 2\n'
  printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
  marker_end ghost
} > "$d/docs/census.md"
before_d2="$(treesum "$d")"
res "d2. good block + block with a missing emitter -> rc 2" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "git does not track it"
res "d2. and the good block was NOT regenerated either" "$(treesum "$d")" "$before_d2"

# ---------------------------------------------------------------------------
# e. the emitter exits non-zero
# ---------------------------------------------------------------------------
d="$LAB/e"; build_repo "$d" scripts/gates/lib/angry_census.py:angry
doc_conflict_inside "$d" scripts/gates/lib/angry_census.py
cp "$d/docs/census.md" "$LAB/e.before"
res "e. the emitter exits non-zero -> rc 2" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "exited 3 in write mode"
res "e. and the subject is back byte-for-byte" \
    "$(cmp -s "$LAB/e.before" "$d/docs/census.md" && echo same || echo different)" same
res "e. the emitter really did run (so the 2 is measured, not assumed)" \
    "$([ -e "$d/.emitter-ran" ] && echo present || echo absent)" present

# ---------------------------------------------------------------------------
# f. an emitter that writes nothing. rc 0 here would mean "resolved" about a
#    file that still carries one branch's stale figures.
# ---------------------------------------------------------------------------
d="$LAB/f"; build_repo "$d" scripts/gates/lib/lazy_census.py:lazy
doc_conflict_inside "$d" scripts/gates/lib/lazy_census.py
cp "$d/docs/census.md" "$LAB/f.before"
res "f. a regeneration that is a NO-OP -> rc 2, never 0" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "NO-OP"
res "f. and the subject is back byte-for-byte" \
    "$(cmp -s "$LAB/f.before" "$d/docs/census.md" && echo same || echo different)" same

# ---------------------------------------------------------------------------
# g. no unmerged file and no PATH: nothing to measure is not a pass
# ---------------------------------------------------------------------------
d="$LAB/g"; build_repo "$d"
res "g. no unmerged file and no PATH -> rc 2" "$(run_tool "$d" "$TOOL")" 2 "there are no unmerged files"

# ---------------------------------------------------------------------------
# h. a begin marker with no end
# ---------------------------------------------------------------------------
d="$LAB/h"; build_repo "$d"
{ printf '# A block that never closes\n\n'
  marker_begin census scripts/gates/lib/fake_census.py
  printf -- '- files counted: 2\n'
  printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
  printf '\nand no end marker anywhere.\n'
} > "$d/docs/census.md"
before="$(treesum "$d")"
res "h. begin marker with no end -> rc 2" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "has no matching census:end"
res "h. and nothing was written" "$(treesum "$d")" "$before"

# ---------------------------------------------------------------------------
# i. two generated regions in one file, a conflict in each
# ---------------------------------------------------------------------------
d="$LAB/i"; build_repo "$d"
{ printf '# Two generated blocks\n\n'
  marker_begin census scripts/gates/lib/fake_census.py
  printf -- '- files counted: 2\n'
  printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
  marker_end census
  printf '\nProse between the two blocks.\n\n'
  marker_begin census2 scripts/gates/lib/fake_census.py
  printf -- '- files counted: 2\n'
  printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
  marker_end census2
} > "$d/docs/census.md"
res "i. two regions, a conflict in each -> rc 0" "$(run_tool "$d" "$TOOL" docs/census.md)" 0 "regenerated"
res "i. BOTH blocks were regenerated" "$(grep -c '^- files counted: 3$' "$d/docs/census.md")" 2
res "i. and no conflict marker survives" \
    "$(grep -c -e '^<<<<<<< ' -e '^=======$' -e '^>>>>>>> ' "$d/docs/census.md")" 0

# ---------------------------------------------------------------------------
# j. SECURITY: the emitter path comes out of a file a branch under review wrote.
#    Each path below points at a REAL, working emitter, so the only thing
#    between it and an execution is the rule under test - and the sentinel
#    proves the difference between "reported" and "not run".
# ---------------------------------------------------------------------------
d="$LAB/j1"; build_repo "$d"
doc_conflict_inside "$d" "$d/scripts/gates/lib/fake_census.py"
before="$(treesum "$d")"
res "j1. an ABSOLUTE emitter path -> rc 2" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "it is an absolute path"
res "j1. and it was not executed" "$([ -e "$d/.emitter-ran" ] && echo present || echo absent)" absent
res "j1. and nothing was written" "$(treesum "$d")" "$before"

d="$LAB/j2"; build_repo "$d"
doc_conflict_inside "$d" "scripts/../scripts/gates/lib/fake_census.py"
before="$(treesum "$d")"
res "j2. a .. segment -> rc 2 (git would have normalised it away)" \
    "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "it contains a .. segment"
res "j2. and it was not executed" "$([ -e "$d/.emitter-ran" ] && echo present || echo absent)" absent
res "j2. and nothing was written" "$(treesum "$d")" "$before"

d="$LAB/j3"; build_repo "$d" tools/evil_census.py:normal   # tracked by build_repo's commit
doc_conflict_inside "$d" tools/evil_census.py
before="$(treesum "$d")"
res "j3. tracked, but outside scripts/ -> rc 2" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "does not live under scripts/"
res "j3. and it was not executed" "$([ -e "$d/.emitter-ran" ] && echo present || echo absent)" absent
res "j3. and nothing was written" "$(treesum "$d")" "$before"

d="$LAB/j4"; build_repo "$d"
emitter "$d" scripts/gates/lib/untracked_census.py normal   # on disk, never committed
doc_conflict_inside "$d" scripts/gates/lib/untracked_census.py
before="$(treesum "$d")"
res "j4. under scripts/ but untracked -> rc 2" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "git does not track it"
res "j4. and it was not executed" "$([ -e "$d/.emitter-ran" ] && echo present || echo absent)" absent
res "j4. and nothing was written" "$(treesum "$d")" "$before"

# ---------------------------------------------------------------------------
# k. --check classifies and writes NOTHING
# ---------------------------------------------------------------------------
d="$LAB/k"; build_repo "$d"
doc_conflict_inside "$d"
before="$(treesum "$d")"
res "k. --check on the headline case -> rc 0" "$(run_tool "$d" "$TOOL" --check docs/census.md)" 0 "I have written nothing"
res "k. same classification as the real run" "$(grep -c 'generated hunk    docs/census.md' "$LAB/out.txt")" 1
res "k. the tree is byte-identical" "$(treesum "$d")" "$before"
res "k. and no emitter was executed, not even in check mode" \
    "$([ -e "$d/.emitter-ran" ] && echo present || echo absent)" absent

# ---------------------------------------------------------------------------
# l. the write lands, and the emitter's own check mode still says no
# ---------------------------------------------------------------------------
d="$LAB/l"; build_repo "$d" scripts/gates/lib/flaky_census.py:flaky
doc_conflict_inside "$d" scripts/gates/lib/flaky_census.py
cp "$d/docs/census.md" "$LAB/l.before"
res "l. check mode still red after the write -> rc 2" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "check mode of scripts/gates/lib/flaky_census.py still exits 1"
res "l. and the subject is back byte-for-byte" \
    "$(cmp -s "$LAB/l.before" "$d/docs/census.md" && echo same || echo different)" same

# extra: a subject with no conflict at all is not a quiet success
d="$LAB/m"; build_repo "$d"
res "a subject with no conflict marker -> rc 2" "$(run_tool "$d" "$TOOL" docs/census.md)" 2 "carries no conflict marker"

# extra: the shapes a person actually types. These exist because the subject
# path is turned into a repo-relative one by stripping the root prefix, and on
# macOS a temporary directory is reached under `/var` while git reports the same
# directory under its resolved spelling, which carries a `/private` prefix in
# front of it - one directory, two spellings. Without `pwd -P` on both sides
# every absolute subject here would be reported as "outside this work tree",
# which is a refusal dressed up as a security finding.
#
# The spelling is described rather than typed out, because gate-machine-identity
# reads that shape as a path belonging to one laptop and this file is not in its
# allowance list. It found this line in CI and not here, for a reason worth
# writing down: the gate's subjects are the VERSIONED files, so while these three
# files were still untracked the whole local suite measured a tree that did not
# contain them.
d="$LAB/n1"; build_repo "$d"; doc_conflict_inside "$d"
res "a subject given as an ABSOLUTE path -> rc 0" "$(run_tool "$d" "$TOOL" "$d/docs/census.md")" 0 "regenerated"
res "n1. and it really regenerated" "$(grep -c '^- files counted: 3$' "$d/docs/census.md")" 1

d="$LAB/n2"; build_repo "$d"; doc_conflict_inside "$d"
res "a subject given from a SUBDIRECTORY -> rc 0" "$(run_tool "$d/docs" "$TOOL" census.md)" 0 "regenerated"
res "n2. and it really regenerated" "$(grep -c '^- files counted: 3$' "$d/docs/census.md")" 1

d="$LAB/n3"; build_repo "$d"
res "a subject OUTSIDE the work tree -> rc 2" "$(run_tool "$d" "$TOOL" /etc/hosts)" 2 "outside this work tree"

# ---------------------------------------------------------------------------
# MUTANTS
#
# Each mutation removes exactly one control from a copy of the tool and re-runs
# the case that control is there for. The case must go RED. A mutation whose
# `sed` matches nothing would prove the opposite of what it looks like it
# proves, so every mutation is checked for having actually changed the file
# before it is run.
# ---------------------------------------------------------------------------
echo
echo "== mutants: knocking out one control at a time"
mut_run=0; mut_caught=0

mutate() {  # <sed expression> -> path of the mutated tool, or empty
  local expr="$1" out="$LAB/mutant.sh"
  sed "$expr" "$TOOL" > "$out" 2>/dev/null
  if cmp -s "$TOOL" "$out"; then return 1; fi
  printf '%s\n' "$out"
}

mres() {  # <label> <caught: yes|no> [detail]
  mut_run=$((mut_run+1))
  if [ "$2" = yes ]; then
    printf '  CAUGHT    %-54s %s\n' "$1" "${3:-}"; mut_caught=$((mut_caught+1))
  else
    printf '  SURVIVED  %-54s %s\n' "$1" "${3:-}"
    printf '            the battery does NOT notice this. Its green says less than it looks.\n'
    fail=$((fail+1))
  fi
}

# m1: keep "ours" and never run the emitter. Case (a) must stop being rc 0.
if M="$(mutate 's/^RUN_EMITTER=1$/RUN_EMITTER=0/')"; then
  d="$LAB/m1"; build_repo "$d"; doc_conflict_inside "$d"
  rc="$(run_tool "$d" "$M" docs/census.md)"
  ok=0; [ "$rc" = 0 ] && grep -q '^- files counted: 3$' "$d/docs/census.md" && ok=1
  mres "m1 never runs the emitter (case a)" "$([ "$ok" -eq 0 ] && echo yes || echo no)" "rc=$rc"
else
  mres "m1 never runs the emitter (case a)" no "the sed matched nothing"
fi

# m2: write even when a hunk is not generated. Case (c) must stop being rc 1
#     with an untouched tree.
if M="$(mutate 's/^GUARD_NON_GENERATED=1$/GUARD_NON_GENERATED=0/')"; then
  d="$LAB/m2"; build_repo "$d"
  { printf '# mixed\n\n'
    marker_begin census scripts/gates/lib/fake_census.py
    printf -- '- files counted: 2\n'
    printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
    marker_end census
    printf '\n<<<<<<< HEAD\nProse one branch wrote.\n=======\nProse the other wrote.\n>>>>>>> feat/b\n'
  } > "$d/docs/census.md"
  before="$(treesum "$d")"
  rc="$(run_tool "$d" "$M" docs/census.md)"
  ok=0; [ "$rc" = 1 ] && [ "$(treesum "$d")" = "$before" ] && ok=1
  mres "m2 writes despite a hunk needing a human (case c)" "$([ "$ok" -eq 0 ] && echo yes || echo no)" "rc=$rc"
else
  mres "m2 writes despite a hunk needing a human (case c)" no "the sed matched nothing"
fi

# m3: accept an emitter path with `..`. Worth reading the measured result: the
#     mutant still answers 2, because the emitter does not recognise a block
#     whose marker spells its path differently and so writes nothing. The rc
#     alone would have said the control was still there. What moves is the
#     SENTINEL: the untrusted path was executed. That is why case (j2) asserts
#     the sentinel and not only the rc - an exit code is not evidence about what
#     ran.
if M="$(mutate 's/^EMITTER_RULE_DOTDOT=1$/EMITTER_RULE_DOTDOT=0/')"; then
  d="$LAB/m3"; build_repo "$d"; doc_conflict_inside "$d" "scripts/../scripts/gates/lib/fake_census.py"
  rc="$(run_tool "$d" "$M" docs/census.md)"
  ran=absent; [ -e "$d/.emitter-ran" ] && ran=present
  ok=0; [ "$rc" = 2 ] && [ "$ran" = absent ] && ok=1
  mres "m3 accepts a .. emitter path (case j2)" "$([ "$ok" -eq 0 ] && echo yes || echo no)" "rc=$rc, emitter $ran"
else
  mres "m3 accepts a .. emitter path (case j2)" no "the sed matched nothing"
fi

# m4: stop recording an emitter the tool refuses. Case (d2) must stop being
#     rc 2: the good block regenerates, the block with the missing emitter keeps
#     one branch's stale figures, and the run reports success.
if M="$(mutate 's/^GUARD_BAD_EMITTER=1$/GUARD_BAD_EMITTER=0/')"; then
  d="$LAB/m4"; build_repo "$d"
  { printf '# Two blocks, one emitter missing\n\n'
    marker_begin census scripts/gates/lib/fake_census.py
    printf -- '- files counted: 2\n'
    printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
    marker_end census
    printf '\n'
    marker_begin ghost scripts/gates/lib/ghost_census.py
    printf -- '- files counted: 2\n'
    printf '<<<<<<< HEAD\n- files: a.txt, one.txt\n=======\n- files: b.txt, one.txt\n>>>>>>> feat/b\n'
    marker_end ghost
  } > "$d/docs/census.md"
  before="$(treesum "$d")"
  rc="$(run_tool "$d" "$M" docs/census.md)"
  ok=0; [ "$rc" = 2 ] && [ "$(treesum "$d")" = "$before" ] && ok=1
  mres "m4 says 0 with an emitter it cannot run (case d2)" "$([ "$ok" -eq 0 ] && echo yes || echo no)" "rc=$rc"
else
  mres "m4 says 0 with an emitter it cannot run (case d2)" no "the sed matched nothing"
fi

# m5: stop recording a regeneration that wrote nothing. Case (f) must stop
#     being rc 2 - the tool would answer 0 about a file that never moved.
if M="$(mutate 's/^GUARD_NOOP=1$/GUARD_NOOP=0/')"; then
  d="$LAB/m5"; build_repo "$d" scripts/gates/lib/lazy_census.py:lazy
  doc_conflict_inside "$d" scripts/gates/lib/lazy_census.py
  rc="$(run_tool "$d" "$M" docs/census.md)"
  ok=0; [ "$rc" = 2 ] && ok=1
  mres "m5 says 0 when the regeneration is a no-op (case f)" "$([ "$ok" -eq 0 ] && echo yes || echo no)" "rc=$rc"
else
  mres "m5 says 0 when the regeneration is a no-op (case f)" no "the sed matched nothing"
fi

# m6: drop the "under scripts/" rule. Case (j3) must stop being rc 2 with the
#     sentinel absent: tools/evil_census.py is tracked and works.
if M="$(mutate 's/^EMITTER_RULE_PREFIX=1$/EMITTER_RULE_PREFIX=0/')"; then
  d="$LAB/m6"; build_repo "$d" tools/evil_census.py:normal
  doc_conflict_inside "$d" tools/evil_census.py
  rc="$(run_tool "$d" "$M" docs/census.md)"
  ran=absent; [ -e "$d/.emitter-ran" ] && ran=present
  ok=0; [ "$rc" = 2 ] && [ "$ran" = absent ] && ok=1
  mres "m6 runs an emitter outside scripts/ (case j3)" "$([ "$ok" -eq 0 ] && echo yes || echo no)" "rc=$rc, emitter $ran"
else
  mres "m6 runs an emitter outside scripts/ (case j3)" no "the sed matched nothing"
fi

echo
echo "  mutants: $mut_caught caught / $mut_run run"
echo "  $pass PASS / $fail FAIL"
[ "$fail" -eq 0 ] || exit 1
exit 0
