version: 2.1

orbs:
  node: circleci/node@5.1

jobs:
  sdk-test:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - node/install-packages
      - run: npm test

  sdk-publish:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - node/install-packages
      - run: npm publish

workflows:
  sdk:
    jobs:
      - sdk-test
      - sdk-publish:
          context: sdk-npm-publish
          requires: [sdk-test]
          filters:
            branches:
              only: main
