#!/usr/bin/env python3
"""doc_census.py — the census sentence of docs/gate-requirements.md, emitted
from the tree instead of typed by hand.

WHY THIS EXISTS
    The status paragraph of docs/gate-requirements.md said, in prose:
    `Seventeen gates execute on every push and pull request` and `Eight have
    their own self-test battery`. Measured on this tree at 6066048 the figures
    were 34 and 23 - the paragraph was written when the suite was a third of its
    present size and nothing has read it since. It also described three lanes
    where the runner has four: the gate that measures the live repository
    (LIVE_SCOPED) appears in no sentence at all, so a whole lane was invisible
    to a reader counting from the document.

    A number in prose looks exactly as authoritative when it is wrong. The fix
    that lasts is not a corrected number, it is a number nobody types: this
    module RENDERS the sentence from the tree, `--write` puts it between the
    markers, and gate-doc-census.sh fails when what is written is not what the
    tree counts.

WHAT IT COUNTS (and how, so that the arithmetic is auditable)
    gates      files matching scripts/gates/gate-*.sh that are NOT *.selftest.sh
    selftests  files matching scripts/gates/gate-*.selftest.sh
    pr         names in PR_SCOPED       in scripts/gates/run-all.sh
    external   names in EXTERNAL_SCOPED in scripts/gates/run-all.sh
    live       names in LIVE_SCOPED     in scripts/gates/run-all.sh
    push_pr    gates - (pr + external + live)

    The glob is then CROSS-CHECKED against `run-all.sh --list`, which is the
    runner's own answer to "what is a gate here". If the two disagree the answer
    is 2, never a number: two instruments with one question is how a census goes
    quietly wrong (run-all.sh discovers, this module counts, and only their
    agreement is evidence). `--list` executes no gate, so there is no recursion.

EXIT CODES (repo contract: rc=0 never means "I did not check it")
    0  the block in the document is what the tree counts
    1  it is not, and the difference is printed line by line
    2  I could not measure: no document, no markers, no run-all.sh, a scope
       declaration that no longer parses, a --list that answers nothing, or a
       tree with no gates in it.
"""

import argparse
import glob
import os
import re
import subprocess
import sys

BEGIN = "<!-- census:begin (generated by scripts/gates/lib/doc_census.py — do not edit by hand) -->"
END = "<!-- census:end -->"
DOC_REL = "docs/gate-requirements.md"

OK, FAIL, UNMEASURABLE = 0, 1, 2


class Unmeasurable(Exception):
    pass


def scope_list(runall_text, name):
    """The names in a scope declaration of run-all.sh, or Unmeasurable.

    Matched as an assignment at the start of a line with a single-quoted value,
    which is the only spelling this repository uses. A renamed or reshaped
    declaration is NOT an empty list: an empty list would silently inflate the
    push/pull-request count, which is the failure this module exists to stop.
    """
    m = re.search(r"(?m)^%s='([^']*)'" % re.escape(name), runall_text)
    if m is None:
        raise Unmeasurable(
            "scripts/gates/run-all.sh has no line `%s='...'`: the runner's lanes "
            "cannot be counted, and an absent lane reads exactly like an empty one" % name
        )
    return [w for w in m.group(1).split() if w]


def census(root):
    gates_dir = os.path.join(root, "scripts", "gates")
    if not os.path.isdir(gates_dir):
        raise Unmeasurable("no scripts/gates/ under %s" % root)

    every = sorted(os.path.basename(p) for p in glob.glob(os.path.join(gates_dir, "gate-*.sh")))
    selftests = [n for n in every if n.endswith(".selftest.sh")]
    gates = [n for n in every if not n.endswith(".selftest.sh")]
    if not gates:
        raise Unmeasurable("no gate-*.sh in %s: a census of nothing is not a census" % gates_dir)

    runall = os.path.join(gates_dir, "run-all.sh")
    if not os.path.isfile(runall):
        raise Unmeasurable("scripts/gates/run-all.sh is missing: nothing declares the lanes")
    text = open(runall, encoding="utf-8", errors="replace").read()
    pr = scope_list(text, "PR_SCOPED")
    external = scope_list(text, "EXTERNAL_SCOPED")
    live = scope_list(text, "LIVE_SCOPED")

    # the runner's own answer, so the count is not read off the scaffolding alone
    try:
        proc = subprocess.run(
            ["bash", runall, "--list"], cwd=root, capture_output=True, text=True, timeout=120
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise Unmeasurable("could not run run-all.sh --list: %s" % exc)
    # --list prints the gates it WOULD run here, one name per line, plus a `· ...`
    # line for each one it is skipping. Only the bare names are read.
    listed = sorted(
        l.strip() for l in proc.stdout.splitlines() if re.fullmatch(r"gate-[A-Za-z0-9._-]+\.sh", l.strip())
    )
    if proc.returncode != 0 or not listed:
        raise Unmeasurable(
            "run-all.sh --list answered rc=%d with %d name(s): the runner did not tell me "
            "what it considers a gate" % (proc.returncode, len(listed))
        )
    scoped = sorted(set(pr) | set(external) | set(live))
    expect = sorted(n for n in gates if n not in scoped)
    if listed != expect:
        only_runner = [n for n in listed if n not in expect]
        only_here = [n for n in expect if n not in listed]
        raise Unmeasurable(
            "run-all.sh --list and this census disagree about which gates run on a push "
            "(only the runner: %s | only this count: %s)"
            % (", ".join(only_runner) or "-", ", ".join(only_here) or "-")
        )
    for name in scoped:
        if name not in gates:
            raise Unmeasurable(
                "run-all.sh defers '%s' and no such gate exists: a lane for a gate that is "
                "gone counts a gate that is not there" % name
            )
    return {
        "gates": len(gates),
        "selftests": len(selftests),
        "pr": len(pr),
        "external": len(external),
        "live": len(live),
        "push_pr": len(listed),
    }


def render(c):
    """The sentence, as the document carries it: a blockquote, one fact per line."""
    return "\n".join(
        [
            BEGIN,
            "> **Status.** Partly running, partly specification, and the table below says",
            "> which is which. %d gate scripts live in `scripts/gates/`, and %d of them carry"
            % (c["gates"], c["selftests"]),
            "> their own self-test battery. %d execute on every push and pull request through"
            % c["push_pr"],
            "> `.github/workflows/ci.yml`; %d run where they can only run — in a pull request —"
            % c["pr"],
            "> through `.github/workflows/issue-closure-gate.yml`; %d runs where its input"
            % c["external"],
            "> exists, in `.github/workflows/scorecard.yml`; and %d measures the live repository"
            % c["live"],
            "> and is deferred BY NAME, with its reason, in `scripts/gates/run-all.sh`. These",
            "> figures are counted from the tree by `scripts/gates/lib/doc_census.py`; editing",
            "> them here turns `gate-doc-census.sh` red rather than making them true.",
            END,
        ]
    )


def block_of(doc_text):
    i = doc_text.find(BEGIN)
    j = doc_text.find(END)
    if i < 0 or j < 0:
        raise Unmeasurable(
            "%s carries no census block: expected the markers %s ... %s. A document with no "
            "marker is not a document that agrees, it is one nothing can check." % (DOC_REL, BEGIN, END)
        )
    if j < i:
        raise Unmeasurable("%s carries the census markers in the wrong order" % DOC_REL)
    return doc_text[i : j + len(END)], i, j + len(END)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=os.environ.get("EHS_REPO_ROOT", "."))
    ap.add_argument("--write", action="store_true", help="put the rendered block in the document")
    ap.add_argument("--print", dest="show", action="store_true", help="print the block and stop")
    args = ap.parse_args(argv)

    root = os.path.abspath(args.root)
    try:
        c = census(root)
    except Unmeasurable as exc:
        print("[COULD NOT MEASURE] %s" % exc, file=sys.stderr)
        return UNMEASURABLE
    want = render(c)
    if args.show:
        print(want)
        return OK

    doc_path = os.path.join(root, DOC_REL)
    if not os.path.isfile(doc_path):
        print("[COULD NOT MEASURE] %s is missing" % DOC_REL, file=sys.stderr)
        return UNMEASURABLE
    text = open(doc_path, encoding="utf-8").read()
    try:
        have, i, j = block_of(text)
    except Unmeasurable as exc:
        print("[COULD NOT MEASURE] %s" % exc, file=sys.stderr)
        return UNMEASURABLE

    if args.write:
        if have != want:
            open(doc_path, "w", encoding="utf-8").write(text[:i] + want + text[j:])
            print("rewrote the census block of %s" % DOC_REL)
        else:
            print("the census block of %s was already current" % DOC_REL)
        return OK

    print(
        "counted in the tree: %d gates, %d self-tests, %d on push/PR, %d PR-only, "
        "%d external, %d live" % (c["gates"], c["selftests"], c["push_pr"], c["pr"], c["external"], c["live"])
    )
    if have == want:
        print("the census block of %s says exactly that" % DOC_REL)
        return OK

    print("[FAIL] %s does not say what the tree counts:" % DOC_REL, file=sys.stderr)
    hl, wl = have.splitlines(), want.splitlines()
    for n in range(max(len(hl), len(wl))):
        a = hl[n] if n < len(hl) else "(no line)"
        b = wl[n] if n < len(wl) else "(no line)"
        if a != b:
            print("  line %-2d written : %s" % (n + 1, a), file=sys.stderr)
            print("  line %-2d counted : %s" % (n + 1, b), file=sys.stderr)
    print("  fix with: python3 scripts/gates/lib/doc_census.py --write", file=sys.stderr)
    return FAIL


if __name__ == "__main__":
    sys.exit(main())
