#!/usr/bin/env python3
"""doc_census.py — the census sentence of docs/gate-requirements.md, emitted
from the tree instead of typed by hand.

WHY THIS EXISTS
    The status paragraph of docs/gate-requirements.md said, in prose:
    `Seventeen gates execute on every push and pull request` and `Eight have
    their own self-test battery`. Measured on this tree at 6066048 the figures
    were 34 and 23 - the paragraph was written when the suite was a third of its
    present size and nothing has read it since. It also described three lanes
    where the runner has four: the gate that measures the live repository
    (LIVE_SCOPED) appears in no sentence at all, so a whole lane was invisible
    to a reader counting from the document.

    A number in prose looks exactly as authoritative when it is wrong. The fix
    that lasts is not a corrected number, it is a number nobody types: this
    module RENDERS the sentence from the tree, `--write` puts it between the
    markers, and gate-doc-census.sh fails when what is written is not what the
    tree counts.

WHAT IT COUNTS (and how, so that the arithmetic is auditable)
    gates      files matching scripts/gates/gate-*.sh that are NOT *.selftest.sh
    selftests  files matching scripts/gates/gate-*.selftest.sh
    pr         names in PR_SCOPED       in scripts/gates/run-all.sh
    external   names in EXTERNAL_SCOPED in scripts/gates/run-all.sh
    live       names in LIVE_SCOPED     in scripts/gates/run-all.sh
    slow       names in SLOW_SCOPED     (declared as a FILE the runner reads)
    push_pr    gates - (pr + external + live + slow)

    The lanes are DISCOVERED, not listed here: every `*_SCOPED=` and
    `*_SCOPED_FILE=` assignment at the start of a line in run-all.sh is one
    lane, and a lane whose name this module does not know is answered 2. The
    reason is the defect this module was written for, one level up: the old
    paragraph described three lanes where the runner had four, and a census
    that also knows three would have counted the fourth lane's gates as running
    on every push - a wrong number, not a missing one. The cost lane arrived
    exactly that way, declared as a file (`SLOW_SCOPED_FILE`) rather than as an
    inline list, and a reader of three names would not have seen it.

    The glob is then CROSS-CHECKED against `run-all.sh --list`, which is the
    runner's own answer to "what is a gate here". If the two disagree the answer
    is 2, never a number: two instruments with one question is how a census goes
    quietly wrong (run-all.sh discovers, this module counts, and only their
    agreement is evidence). `--list` executes no gate, so there is no recursion.

EXIT CODES (repo contract: rc=0 never means "I did not check it")
    0  the block in the document is what the tree counts
    1  it is not, and the difference is printed line by line
    2  I could not measure: no document, no markers, no run-all.sh, a scope
       declaration that no longer parses, a --list that answers nothing, or a
       tree with no gates in it.
"""

import argparse
import glob
import os
import re
import subprocess
import sys

BEGIN = "<!-- census:begin (generated by scripts/gates/lib/doc_census.py — do not edit by hand) -->"
END = "<!-- census:end -->"
DOC_REL = "docs/gate-requirements.md"
SLOW_DECL_REL = "scripts/gates/data/slow-scoped.txt"

OK, FAIL, UNMEASURABLE = 0, 1, 2


class Unmeasurable(Exception):
    pass


KNOWN_LANES = ("PR_SCOPED", "EXTERNAL_SCOPED", "LIVE_SCOPED", "SLOW_SCOPED")
REQUIRED_LANES = ("PR_SCOPED", "EXTERNAL_SCOPED", "LIVE_SCOPED")
LANE_DECL = re.compile(r"(?m)^([A-Z][A-Z0-9_]*_SCOPED(?:_FILE)?)=(.*)$")


def _lane_path(rhs, decl, gates_dir):
    """The file a `*_SCOPED_FILE=` declaration points at, without a shell."""
    v = rhs.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "'\"":
        v = v[1:-1]
    elif not v or " " in v:
        raise Unmeasurable(
            "run-all.sh declares %s as %r and this census does not read that shape: "
            "a lane it cannot read counts as a lane that is empty" % (decl, rhs.strip())
        )
    p = v.replace("${SELF_DIR}", gates_dir).replace("$SELF_DIR", gates_dir)
    if "$" in p:
        raise Unmeasurable(
            "run-all.sh points %s at %r and this census cannot expand it without running "
            "the shell: an unexpanded path reads exactly like an absent lane" % (decl, v)
        )
    if p == v and not os.path.isabs(p):
        # No $SELF_DIR and not absolute: relative to a working directory only the
        # shell knows. Joining it to the gates directory would be a guess, and a
        # guess that misses reads back as a lane with nothing in it.
        raise Unmeasurable(
            "run-all.sh points %s at the relative path %r with no $SELF_DIR, and this "
            "census cannot tell what it is relative to" % (decl, v)
        )
    return p


def _names_in_file(path, decl):
    """The names a lane file carries. Absent is empty - unreadable is not."""
    if not os.path.exists(path):
        # run-all.sh says the same thing out loud when the file is not there:
        # nothing is deferred for that reason, every gate found runs here.
        return []
    if not os.access(path, os.R_OK):
        raise Unmeasurable(
            "%s points at %s, which is there and unreadable: a lane I cannot read "
            "reads exactly like an empty one" % (decl, path)
        )
    try:
        text = open(path, encoding="utf-8", errors="replace").read()
    except OSError as exc:
        raise Unmeasurable("%s points at %s and I could not read it: %s" % (decl, path, exc))
    names = []
    for line in text.splitlines():
        names.extend(w for w in line.split("#", 1)[0].split() if w)
    return names


def lanes(runall_text, gates_dir, origin=None):
    """Every scope declaration run-all.sh carries, read by its own shape.

    Matched as an assignment at the start of a line, which is the only spelling
    this repository uses; the copies inside an `if` are indented and are the
    runner's own working-out, not a declaration. A renamed or reshaped
    declaration is NOT an empty list: an empty list would silently inflate the
    push/pull-request count, which is the failure this module exists to stop.
    """
    found = {}
    for m in LANE_DECL.finditer(runall_text):
        decl, rhs = m.group(1), m.group(2)
        lane = decl[: -len("_FILE")] if decl.endswith("_FILE") else decl
        if lane in found:
            raise Unmeasurable(
                "run-all.sh declares the %s lane more than once at the start of a line, and "
                "this census cannot tell which declaration the runner obeys" % lane
            )
        if decl.endswith("_FILE"):
            path = _lane_path(rhs, decl, gates_dir)
            if origin is not None:
                origin[lane] = path
            found[lane] = _names_in_file(path, decl)
            continue
        q = re.match(r"'([^']*)'\s*$", rhs.strip())
        if q is None:
            raise Unmeasurable(
                "run-all.sh declares %s as %r: this census reads a lane written as "
                "%s='name name', and a shape it cannot read would count that lane's "
                "gates as running on every push" % (decl, rhs.strip(), decl)
            )
        if origin is not None:
            origin[lane] = os.path.join(gates_dir, "run-all.sh")
        found[lane] = [w for w in q.group(1).split() if w]
    return found


def census(root):
    gates_dir = os.path.join(root, "scripts", "gates")
    if not os.path.isdir(gates_dir):
        raise Unmeasurable("no scripts/gates/ under %s" % root)

    every = sorted(os.path.basename(p) for p in glob.glob(os.path.join(gates_dir, "gate-*.sh")))
    selftests = [n for n in every if n.endswith(".selftest.sh")]
    gates = [n for n in every if not n.endswith(".selftest.sh")]
    if not gates:
        raise Unmeasurable("no gate-*.sh in %s: a census of nothing is not a census" % gates_dir)

    runall = os.path.join(gates_dir, "run-all.sh")
    if not os.path.isfile(runall):
        raise Unmeasurable("scripts/gates/run-all.sh is missing: nothing declares the lanes")
    text = open(runall, encoding="utf-8", errors="replace").read()
    origin = {}
    lane = lanes(text, gates_dir, origin)
    for name in REQUIRED_LANES:
        if name not in lane:
            raise Unmeasurable(
                "scripts/gates/run-all.sh has no line `%s='...'`: the runner's lanes "
                "cannot be counted, and an absent lane reads exactly like an empty one" % name
            )
    unknown = sorted(n for n in lane if n not in KNOWN_LANES)
    if unknown:
        raise Unmeasurable(
            "run-all.sh declares the lane(s) %s and this census has no name for them: an "
            "unknown lane is not an empty one, it is a set of gates that would be counted "
            "as running on every push" % ", ".join(unknown)
        )
    pr = lane["PR_SCOPED"]
    external = lane["EXTERNAL_SCOPED"]
    live = lane["LIVE_SCOPED"]
    slow = lane.get("SLOW_SCOPED", [])
    slow_at = SLOW_DECL_REL
    if "SLOW_SCOPED" in origin:
        where = origin["SLOW_SCOPED"]
        slow_at = os.path.relpath(where, root) if os.path.isabs(where) else where

    # the runner's own answer, so the count is not read off the scaffolding alone.
    # It is asked the question this census answers - which gates run ON A PUSH -
    # and a push carries no local cost override, so the probe must not inherit
    # one. It did, and the damage was not hypothetical: ci.yml's `counts` job
    # sets EHS_SLOW_GATES=1 for the whole job, so inside the one lane where this
    # census is ever measured `--list` named the deferred gate, this count did
    # not, and every measurement there was an Unmeasurable. A generated sentence
    # that changes with the shell is not a property of the tree.
    probe_env = dict(os.environ)
    probe_env.pop("EHS_SLOW_GATES", None)
    try:
        proc = subprocess.run(
            ["bash", runall, "--list"], cwd=root, capture_output=True, text=True,
            timeout=120, env=probe_env
        )
    except (OSError, subprocess.SubprocessError) as exc:
        raise Unmeasurable("could not run run-all.sh --list: %s" % exc)
    # --list prints the gates it WOULD run here, one name per line, plus a `· ...`
    # line for each one it is skipping. Only the bare names are read.
    listed = sorted(
        l.strip() for l in proc.stdout.splitlines() if re.fullmatch(r"gate-[A-Za-z0-9._-]+\.sh", l.strip())
    )
    if proc.returncode != 0 or not listed:
        raise Unmeasurable(
            "run-all.sh --list answered rc=%d with %d name(s): the runner did not tell me "
            "what it considers a gate" % (proc.returncode, len(listed))
        )
    scoped = sorted(set(pr) | set(external) | set(live) | set(slow))
    expect = sorted(n for n in gates if n not in scoped)
    if listed != expect:
        only_runner = [n for n in listed if n not in expect]
        only_here = [n for n in expect if n not in listed]
        raise Unmeasurable(
            "run-all.sh --list and this census disagree about which gates run on a push "
            "(only the runner: %s | only this count: %s)"
            % (", ".join(only_runner) or "-", ", ".join(only_here) or "-")
        )
    for name in scoped:
        # A cost lane defers the battery beside the gate, on purpose: deferring
        # only the gate moves the cost into --selftests instead of removing it.
        # So a scoped name may be either, and a name that is neither is a lane
        # pointing at something the tree no longer has.
        if name not in gates and name not in selftests:
            raise Unmeasurable(
                "run-all.sh defers '%s' and the tree has no such gate or self-test battery: "
                "a lane for something that is gone counts a control that is not there" % name
            )
    return {
        "gates": len(gates),
        "selftests": len(selftests),
        "pr": len(pr),
        "external": len(external),
        "live": len(live),
        "slow": len(slow),
        "slow_at": slow_at,
        "push_pr": len(listed),
    }


def render(c):
    """The sentence, as the document carries it: a blockquote, one fact per line.

    The cost lane gets a clause of its own ONLY when it has gates in it, so a
    tree without that lane renders the sentence it always rendered.
    """
    lines = [
            BEGIN,
            "> **Status.** Partly running, partly specification, and the table below says",
            "> which is which. %d gate scripts live in `scripts/gates/`, and %d of them carry"
            % (c["gates"], c["selftests"]),
            "> their own self-test battery. %d execute on every push and pull request through"
            % c["push_pr"],
            "> `.github/workflows/ci.yml`; %d run where they can only run — in a pull request —"
            % c["pr"],
            "> through `.github/workflows/issue-closure-gate.yml`; %d %s where its input"
            % (c["external"], "runs" if c["external"] == 1 else "run"),
            "> exists, in `.github/workflows/scorecard.yml`; and %d %s the live repository"
            % (c["live"], "measures" if c["live"] == 1 else "measure"),
    ]
    # The number decides the verb, here as in the slow clause below. It was not
    # so: the live clause was written when the lane held one gate and read
    # `2 measures the live repository ... with its reason` the day it held two.
    its_reason = "its reason" if c["live"] == 1 else "their reasons"
    is_deferred = "is deferred" if c["live"] == 1 else "are deferred"
    if c.get("slow"):
        # append, never assign: the first draft of this clause wrote over
        # lines[-1] and silently deleted the live lane from the sentence - the
        # very defect this module exists to stop, committed by the fix for it.
        lines.append("> and %s BY NAME, with %s, in `scripts/gates/run-all.sh`; and"
                     % (is_deferred, its_reason))
        lines.append(
            "> %d %s in a CI job of %s, deferred for cost by name in"
            % (c["slow"], "runs" if c["slow"] == 1 else "run", "its own" if c["slow"] == 1 else "their own")
        )
        lines.append("> `%s`. These" % c.get("slow_at", SLOW_DECL_REL))
    else:
        lines.append("> and %s BY NAME, with %s, in `scripts/gates/run-all.sh`. These"
                     % (is_deferred, its_reason))
    lines.append("> figures are counted from the tree by `scripts/gates/lib/doc_census.py`; editing")
    lines.append("> them here turns `gate-doc-census.sh` red rather than making them true.")
    lines.append(END)
    return "\n".join(lines)


def block_of(doc_text):
    i = doc_text.find(BEGIN)
    j = doc_text.find(END)
    if i < 0 or j < 0:
        raise Unmeasurable(
            "%s carries no census block: expected the markers %s ... %s. A document with no "
            "marker is not a document that agrees, it is one nothing can check." % (DOC_REL, BEGIN, END)
        )
    if j < i:
        raise Unmeasurable("%s carries the census markers in the wrong order" % DOC_REL)
    return doc_text[i : j + len(END)], i, j + len(END)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--root", default=os.environ.get("EHS_REPO_ROOT", "."))
    ap.add_argument("--write", action="store_true", help="put the rendered block in the document")
    ap.add_argument("--print", dest="show", action="store_true", help="print the block and stop")
    args = ap.parse_args(argv)

    root = os.path.abspath(args.root)
    try:
        c = census(root)
    except Unmeasurable as exc:
        print("[COULD NOT MEASURE] %s" % exc, file=sys.stderr)
        return UNMEASURABLE
    want = render(c)
    if args.show:
        print(want)
        return OK

    doc_path = os.path.join(root, DOC_REL)
    if not os.path.isfile(doc_path):
        print("[COULD NOT MEASURE] %s is missing" % DOC_REL, file=sys.stderr)
        return UNMEASURABLE
    text = open(doc_path, encoding="utf-8").read()
    try:
        have, i, j = block_of(text)
    except Unmeasurable as exc:
        print("[COULD NOT MEASURE] %s" % exc, file=sys.stderr)
        return UNMEASURABLE

    if args.write:
        if have != want:
            open(doc_path, "w", encoding="utf-8").write(text[:i] + want + text[j:])
            print("rewrote the census block of %s" % DOC_REL)
        else:
            print("the census block of %s was already current" % DOC_REL)
        return OK

    print(
        "counted in the tree: %d gates, %d self-tests, %d on push/PR, %d PR-only, "
        "%d external, %d live" % (c["gates"], c["selftests"], c["push_pr"], c["pr"], c["external"], c["live"])
    )
    if have == want:
        print("the census block of %s says exactly that" % DOC_REL)
        return OK

    print("[FAIL] %s does not say what the tree counts:" % DOC_REL, file=sys.stderr)
    hl, wl = have.splitlines(), want.splitlines()
    for n in range(max(len(hl), len(wl))):
        a = hl[n] if n < len(hl) else "(no line)"
        b = wl[n] if n < len(wl) else "(no line)"
        if a != b:
            print("  line %-2d written : %s" % (n + 1, a), file=sys.stderr)
            print("  line %-2d counted : %s" % (n + 1, b), file=sys.stderr)
    print("  fix with: python3 scripts/gates/lib/doc_census.py --write", file=sys.stderr)
    return FAIL


if __name__ == "__main__":
    sys.exit(main())
