#!/usr/bin/env bash
# scripts/gh/resolve-generated.sh
#
# Resolves a merge conflict that lies WHOLLY INSIDE A GENERATED REGION by
# regenerating the region, and refuses to touch anything else.
#
# WHY IT EXISTS
#   Measured on this repository, in every iteration of the branch loop: two
#   branches each append a row to docs/gate-requirements.md while a third edits
#   the lines next to them, and the merge conflicts. The conflicting lines sit
#   inside a block that looks like this:
#
#     <!-- census:begin (generated by scripts/gates/lib/doc_census.py - do not edit by hand) -->
#     ... counted figures ...
#     <!-- census:end -->
#
#   A conflict in there is not a decision anybody should be making by hand.
#   BOTH sides are stale: each is a copy of what a program emitted from a tree
#   that no longer exists, and the tree that matters - the merged one - has a
#   third set of figures that neither branch ever saw. Picking "ours" or
#   "theirs" writes a number that was never true of the tree it describes.
#   merge-preview.sh --union fails in the same honest way: it keeps both sides,
#   so the block ends up stating two different counts.
#
#   The resolution is therefore not a choice between the two sides. It is:
#   throw both away and run the program again.
#
# WHAT IT DOES
#   1. Takes the unmerged files of the current tree (or exactly the PATHs given)
#      and finds every conflict hunk in them.
#   2. Classifies each hunk. A hunk is GENERATED when it lies wholly between a
#      begin marker and its end marker, where the begin marker NAMES ITS OWN
#      EMITTER. The emitter is read OUT OF THE FILE, never from a list kept in
#      here: a hard-coded list of "files we know how to regenerate" is exactly
#      the dangling reference this repository keeps finding - the emitter gets
#      renamed, the list goes on naming the old path, and nobody hears about it.
#   3. If EVERY hunk of EVERY subject is generated, it keeps one side textually
#      (they are both stale, and it says so), runs each named emitter in write
#      mode, and then VERIFIES: no conflict marker survived, the emitter's own
#      check mode returns 0, and the file actually MOVED off the side that was
#      kept. A regeneration that wrote nothing is answered with 2, never with 0 -
#      a resolver that writes nothing has resolved nothing.
#   4. If any hunk is not generated it writes NOTHING AT ALL - not even the
#      generated hunks of the other files - and names the file and the lines.
#      Half a resolution leaves a tree nobody reviewed and nobody can review,
#      because the half it did quietly is the half that no longer shows up as a
#      conflict for anyone to look at.
#
# SECURITY - THE EMITTER PATH IS UNTRUSTED INPUT
#   The emitter path arrives INSIDE A CONFLICTED FILE. A conflicted file is a
#   file being merged from a branch under review: text a contributor wrote, that
#   nobody has approved yet, that this tool is about to turn into an execution.
#   That is the shape of the attack - open a pull request whose marker names
#   something else, and wait for a maintainer to resolve a conflict with a tool.
#
#   So, before anything runs, the path must be:
#     - repo-relative, never absolute;
#     - free of any `..` segment, so it cannot climb out of the tree;
#     - under scripts/, so it is inside the area this repository reviews;
#     - TRACKED BY GIT (`git ls-files --error-unmatch`), so it is a reviewed
#       file of this tree and not something the same merge dropped in the
#       working directory.
#   It is invoked as `python3 -- <path> [--write]` with the repo root as the
#   working directory. It is NEVER passed to a shell, never word-split, never
#   interpolated into a command line. A marker naming anything else is answered
#   with rc 2 and the emitter is not executed - not "sanitised", not "fixed up":
#   not executed.
#
# EXIT CODES (repo contract: an rc=0 never means "I did not check")
#   0 = I MEASURED, every hunk was generated, and the regeneration landed
#   1 = I MEASURED, and a hunk is NOT inside a generated region: a human
#       decision remains. Nothing was written.
#   2 = I COULD NOT MEASURE. Not a git work tree; no subject at all; a subject
#       with no conflict marker; a begin marker with no end; an emitter I
#       refuse to run; no python3; an emitter that exits non-zero; a
#       regeneration that leaves the check mode red or changes nothing.
#       Whenever the answer is 2 after anything was written, every subject is
#       restored byte-for-byte from the copy taken before the write.
#
# USAGE
#   scripts/gh/resolve-generated.sh                    # the unmerged files
#   scripts/gh/resolve-generated.sh docs/gate-requirements.md
#   scripts/gh/resolve-generated.sh --check            # classify, write nothing
#
# WHAT IT DOES NOT DO
#   It does not `git add`, it does not commit, and it does not finish the merge.
#   It rewrites the working-tree file and stops, so the resolution shows up in
#   `git diff` and a person still reads it before it becomes a commit.
# ---------------------------------------------------------------------------
set -uo pipefail

# MUTATION ANCHORS.
#   Each control below is one line, assigned a literal, read from nowhere else -
#   not from the environment, not from an option. They are in this shape so that
#   scripts/gh/tests/test-resolve-generated.sh can knock out exactly one control
#   with a one-line `sed` and prove some case of the battery goes red because of
#   it. A control that no mutation can remove is a control whose battery has
#   never been shown to notice it, and this repository has shipped that before:
#   a green that meant nothing because no red was reachable.
#   Knocking out GUARD_BAD_EMITTER degrades the REPORT, never the safety - an
#   emitter this tool refuses to run is still not run.
RUN_EMITTER=1
GUARD_NON_GENERATED=1
GUARD_BAD_EMITTER=1
GUARD_NOOP=1
EMITTER_RULE_ABSOLUTE=1
EMITTER_RULE_DOTDOT=1
EMITTER_RULE_PREFIX=1
EMITTER_RULE_TRACKED=1

CHECK=0
UNMEASURED=0
NON_GENERATED=0

verdict() {  # <rc> <one-line reason>   -- always the last line of a run
  printf '\n== verdict\n'
  case "$1" in
    0) printf '  0 (measured: %s)\n' "$2" ;;
    1) printf '  1 (measured: %s)\n' "$2" ;;
    *) printf '  2 (COULD NOT MEASURE: %s - this is not a pass)\n' "$2" ;;
  esac
}

die2() {  # a precondition that makes the whole run unmeasurable
  printf 'COULD NOT MEASURE: %s\n' "$*" >&2
  verdict 2 "$*"
  exit 2
}

cannot() { UNMEASURED=$((UNMEASURED + 1)); printf '  COULD NOT MEASURE  %s\n' "$*"; }
human()  { NON_GENERATED=$((NON_GENERATED + 1)); printf '  NEEDS A HUMAN      %s\n' "$*"; }
note()   { printf '  %s\n' "$*"; }

while [ $# -gt 0 ]; do
  case "$1" in
    --check) CHECK=1; shift ;;
    -h|--help) sed -n '2,88p' "${BASH_SOURCE[0]}"; exit 0 ;;
    --) shift; break ;;
    -*) printf 'COULD NOT MEASURE: unknown argument %s\n' "$1" >&2
        verdict 2 "unknown argument $1"; exit 2 ;;
    *) break ;;
  esac
done

command -v git >/dev/null 2>&1 || die2 "git is missing"
# python3 is not optional: it is how an emitter is run, and a run that cannot
# run the emitter has measured nothing.
command -v python3 >/dev/null 2>&1 || die2 "python3 is missing, so no emitter could be run"

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
[ -n "$ROOT" ] || die2 "$(pwd -P) is not a git work tree"
# Physical paths on both sides, or the prefix arithmetic below fails silently on
# a macOS temporary directory, where /var is a symlink to /private/var and git
# reports one spelling while the shell reports the other.
ROOT="$(cd "$ROOT" && pwd -P)"
HERE="$(pwd -P)"

TMP="$(mktemp -d "${TMPDIR:-/tmp}/ehs-resolve-generated-XXXXXX")" || die2 "I could not make a scratch directory"
trap 'rm -rf "$TMP"' EXIT
: > "$TMP/subjects"
: > "$TMP/emitters"
: > "$TMP/kept"

printf '\n=== resolve-generated ===\n'
printf 'ROOT      : %s\n' "$ROOT"
if [ "$CHECK" -eq 1 ]; then printf 'MODE      : --check (I classify and write NOTHING)\n'; fi

# ---------------------------------------------------------------------------
# The subjects.
# ---------------------------------------------------------------------------
if [ $# -gt 0 ]; then
  for a in "$@"; do
    case "$a" in
      /*) abs="$a" ;;
      *)  abs="$HERE/$a" ;;
    esac
    d="$(cd "$(dirname "$abs")" 2>/dev/null && pwd -P)" || d=""
    if [ -z "$d" ]; then cannot "$a: its directory does not exist"; continue; fi
    abs="$d/$(basename "$abs")"
    case "$abs" in
      "$ROOT"/*) printf '%s\n' "${abs#"$ROOT"/}" >> "$TMP/subjects" ;;
      *) cannot "$a: it is outside this work tree" ;;
    esac
  done
else
  git -C "$ROOT" diff --name-only --diff-filter=U > "$TMP/subjects" 2>/dev/null \
    || die2 "git could not list the unmerged files"
fi

if ! grep -q . "$TMP/subjects"; then
  # No PATH and no unmerged file is NOT "everything is fine". It is a run with
  # nothing to measure, and a 0 here would let a caller read "no conflict" out
  # of "I was pointed at nothing".
  if [ "$UNMEASURED" -eq 0 ]; then
    cannot "no subject: there are no unmerged files in this tree and no PATH was given"
  fi
  verdict 2 "there was nothing to classify"
  exit 2
fi

# ---------------------------------------------------------------------------
# Classification. Nothing is written in this phase, for any subject.
# ---------------------------------------------------------------------------
# The awk pass does three things in one walk of the file, because they are the
# same walk: it writes the "ours" projection (the file with every conflict
# marker removed, keeping our side), it reports every conflict hunk in ORIGINAL
# line numbers, and it reports every generated region - also in original line
# numbers, which is what turns "wholly inside" into a comparison instead of a
# guess.
#
# Why the projection and not the raw text: a marker may sit on one side of a
# conflict and not on the other, and a scanner walking the raw text would pair a
# begin from our side with an end from theirs. The projection is one coherent
# document, with the conflict markers gone from it by construction.
#
# Single quotes on purpose: every $ below belongs to awk, not to the shell.
# shellcheck disable=SC2016
AWK_SCAN='
BEGIN { inc = 0; side = ""; open = ""; hunks = 0; bad = 0 }
/^<<<<<<< / {
  if (inc) { printf "ERR a second <<<<<<< at line %d: the conflict markers do not balance\n", NR; bad = 1; exit }
  hs = NR; inc = 1; side = "ours"; next
}
/^\|\|\|\|\|\|\| / { if (inc) { side = "base"; next } }
/^=======$/       { if (inc) { side = "theirs"; next } }
/^>>>>>>> /       { if (inc) { printf "HUNK %d %d\n", hs, NR; hunks++; inc = 0; side = ""; next } }
{
  if (inc && side != "ours") next
  print $0 > pf
  line = $0
  if (match(line, /<!--[[:blank:]]*[A-Za-z0-9_][A-Za-z0-9_.-]*:begin[[:blank:]]*\(generated by[[:blank:]]+[^[:blank:])]+/)) {
    m = substr(line, RSTART, RLENGTH)
    ti = index(m, ":begin")
    tag = substr(m, 1, ti - 1)
    sub(/^<!--[[:blank:]]*/, "", tag)
    gi = index(m, "generated by")
    em = substr(m, gi + 12)
    sub(/^[[:blank:]]+/, "", em)
    if (open != "") {
      printf "ERR the %s:begin marker at line %d has no matching %s:end (%s:begin opens at line %d before it closes)\n", open, ostart, open, tag, NR
      bad = 1; exit
    }
    open = tag; ostart = NR; oem = em
    next
  }
  if (open != "" && match(line, /<!--[[:blank:]]*[A-Za-z0-9_][A-Za-z0-9_.-]*:end[[:blank:]]*-->/)) {
    m2 = substr(line, RSTART, RLENGTH)
    t2 = index(m2, ":end")
    tag2 = substr(m2, 1, t2 - 1)
    sub(/^<!--[[:blank:]]*/, "", tag2)
    if (tag2 == open) { printf "REGION %d %d %s %s\n", ostart, NR, oem, open; open = "" }
  }
}
END {
  if (bad) exit
  if (inc)        printf "ERR the conflict hunk that starts at line %d never ends\n", hs
  if (open != "") printf "ERR the %s:begin marker at line %d has no matching %s:end\n", open, ostart, open
  printf "STAT %d\n", hunks
}
'

# A repo-relative path is eligible to be EXECUTED only if every rule below says
# so. Each rule is its own statement, so a battery can remove exactly one and
# see which case notices.
EM_WHY=""
emitter_eligible() {
  em_p="$1"
  EM_WHY=""
  if [ -z "$em_p" ]; then EM_WHY="the marker names no path at all"; return 1; fi
  if [ "$EMITTER_RULE_ABSOLUTE" -eq 1 ]; then
    case "$em_p" in /*) EM_WHY="it is an absolute path"; return 1 ;; esac
  fi
  if [ "$EMITTER_RULE_DOTDOT" -eq 1 ]; then
    # `scripts/../scripts/gates/lib/x.py` passes the prefix rule, and git
    # normalises the `..` away so the tracked rule passes too. Without this rule
    # a `..` path is executed. It is the one rule whose absence no other rule
    # covers, which is why it is tested with a path that would really run.
    case "$em_p" in ..|../*|*/..|*/../*) EM_WHY="it contains a .. segment"; return 1 ;; esac
  fi
  if [ "$EMITTER_RULE_PREFIX" -eq 1 ]; then
    case "$em_p" in scripts/*) : ;; *) EM_WHY="it does not live under scripts/"; return 1 ;; esac
  fi
  if [ "$EMITTER_RULE_TRACKED" -eq 1 ]; then
    git -C "$ROOT" ls-files --error-unmatch -- "$em_p" >/dev/null 2>&1 \
      || { EM_WHY="git does not track it in this tree"; return 1; }
  fi
  return 0
}

IDX=0
printf '\n== classifying\n'
while IFS= read -r rel; do
  [ -n "$rel" ] || continue
  IDX=$((IDX + 1))
  abs="$ROOT/$rel"
  if [ ! -f "$abs" ]; then cannot "$rel: it is not a file in this tree"; continue; fi
  if [ ! -r "$abs" ]; then cannot "$rel: I cannot read it"; continue; fi

  # "Is there a conflict here" is asked of the file itself and never through a
  # pipe: `| grep -q` cannot tell "there is no marker" from "I could not look",
  # and this repository has already reported the second as the first.
  grep -q -e '^<<<<<<< ' "$abs"; g=$?
  case "$g" in
    0) : ;;
    1) cannot "$rel: it carries no conflict marker, so there is nothing here to resolve"; continue ;;
    *) cannot "$rel: grep could not read it (rc $g)"; continue ;;
  esac

  awk -v pf="$TMP/proj.$IDX" "$AWK_SCAN" "$abs" > "$TMP/rec.$IDX" 2>"$TMP/awkerr.$IDX"
  arc=$?
  if [ "$arc" -ne 0 ]; then
    cannot "$rel: awk could not scan it (rc $arc): $(tr '\n' ' ' < "$TMP/awkerr.$IDX")"
    continue
  fi
  [ -f "$TMP/proj.$IDX" ] || : > "$TMP/proj.$IDX"

  : > "$TMP/hunks.$IDX"
  : > "$TMP/regions.$IDX"
  subject_bad=0
  while IFS= read -r recline; do
    kind="${recline%% *}"
    rest="${recline#* }"
    case "$kind" in
      HUNK)   printf '%s\n' "$rest" >> "$TMP/hunks.$IDX" ;;
      REGION) printf '%s\n' "$rest" >> "$TMP/regions.$IDX" ;;
      STAT)   : ;;
      ERR)    cannot "$rel: $rest"; subject_bad=1 ;;
      *)      cannot "$rel: the scanner said something I do not understand: $recline"; subject_bad=1 ;;
    esac
  done < "$TMP/rec.$IDX"
  [ "$subject_bad" -eq 0 ] || continue

  if ! grep -q . "$TMP/hunks.$IDX"; then
    cannot "$rel: it has a <<<<<<< and no complete hunk, so I cannot classify it"
    continue
  fi

  n_gen=0
  while IFS= read -r h; do
    [ -n "$h" ] || continue
    hs="${h%% *}"; he="${h#* }"
    owner=""; owner_tag=""; owner_b=""; owner_e=""
    while IFS= read -r r; do
      [ -n "$r" ] || continue
      rb="${r%% *}";  r2="${r#* }"
      re_="${r2%% *}"; r3="${r2#* }"
      rem="${r3%% *}"; rtag="${r3#* }"
      # WHOLLY inside: the begin marker strictly above the hunk, the end marker
      # strictly below it. A hunk that swallows one of its own markers is not a
      # stale figure - it is a disagreement about the shape of the block, and
      # that is a person's call.
      if [ "$rb" -lt "$hs" ] && [ "$he" -lt "$re_" ]; then
        owner="$rem"; owner_tag="$rtag"; owner_b="$rb"; owner_e="$re_"
        break
      fi
    done < "$TMP/regions.$IDX"

    if [ -z "$owner" ]; then
      human "$rel lines $hs-$he: this hunk is not inside any generated region"
      continue
    fi
    if ! emitter_eligible "$owner"; then
      # Recorded, and NOT run. The anchor below only silences the report; the
      # `continue` that keeps the path away from python3 sits outside it on
      # purpose, so a mutation of the report can never become an execution.
      if [ "$GUARD_BAD_EMITTER" -eq 1 ]; then
        cannot "$rel lines $hs-$he: the $owner_tag:begin marker names an emitter I will not run - $owner: $EM_WHY"
      fi
      continue
    fi
    n_gen=$((n_gen + 1))
    note "generated hunk    $rel lines $hs-$he inside $owner_tag (lines $owner_b-$owner_e), emitter $owner"
    grep -qxF -- "$owner" "$TMP/emitters" || printf '%s\n' "$owner" >> "$TMP/emitters"
  done < "$TMP/hunks.$IDX"

  if [ "$n_gen" -gt 0 ]; then printf '%s %s\n' "$IDX" "$rel" >> "$TMP/kept"; fi
done < "$TMP/subjects"

RC=0
if [ "$UNMEASURED" -gt 0 ]; then
  RC=2
elif [ "$GUARD_NON_GENERATED" -eq 1 ] && [ "$NON_GENERATED" -gt 0 ]; then
  RC=1
fi

if [ "$RC" -eq 1 ]; then
  printf '\n  %d hunk(s) need a person. NOTHING has been written - not even the\n' "$NON_GENERATED"
  printf '  generated hunks of the other files. Resolving half a conflict leaves the\n'
  printf '  other half looking resolved to everyone who reads the diff afterwards.\n'
  verdict 1 "$NON_GENERATED hunk(s) are not inside a generated region; nothing was written"
  exit 1
fi

if [ "$RC" -eq 2 ]; then
  printf '\n  Nothing has been written.\n'
  verdict 2 "$UNMEASURED thing(s) I could not classify or could not run"
  exit 2
fi

if [ "$CHECK" -eq 1 ]; then
  printf '\n== what I would do (and have NOT done)\n'
  while IFS= read -r k; do
    [ -n "$k" ] || continue
    note "keep one side of  ${k#* }   (both sides are stale copies of generated text)"
  done < "$TMP/kept"
  while IFS= read -r e; do
    [ -n "$e" ] || continue
    note "then run          python3 -- $e --write   (cwd $ROOT)"
  done < "$TMP/emitters"
  note "I have written nothing, and I have executed no emitter, not even in check mode."
  verdict 0 "--check: every hunk is generated and every emitter named is one I would run"
  exit 0
fi

# ---------------------------------------------------------------------------
# The write phase. Every subject is copied first, so any 2 from here on can put
# the tree back exactly as it was found.
# ---------------------------------------------------------------------------
printf '\n== resolving\n'
while IFS= read -r k; do
  [ -n "$k" ] || continue
  i="${k%% *}"; rel="${k#* }"
  cp "$ROOT/$rel" "$TMP/orig.$i" || die2 "I could not copy $rel before writing to it"
done < "$TMP/kept"

restore() {
  while IFS= read -r k_r; do
    [ -n "$k_r" ] || continue
    i_r="${k_r%% *}"; rel_r="${k_r#* }"
    if [ -f "$TMP/orig.$i_r" ]; then cp "$TMP/orig.$i_r" "$ROOT/$rel_r"; fi
  done < "$TMP/kept"
  printf '  restored every subject byte-for-byte from the copy taken before the write.\n'
}

while IFS= read -r k; do
  [ -n "$k" ] || continue
  i="${k%% *}"; rel="${k#* }"
  cp "$TMP/proj.$i" "$ROOT/$rel" || { cannot "$rel: I could not write the kept side"; continue; }
  note "kept one side of  $rel   - BOTH sides were stale; the emitter decides what it says"
done < "$TMP/kept"

if [ "$RUN_EMITTER" -eq 1 ]; then
  while IFS= read -r e; do
    [ -n "$e" ] || continue
    ( cd "$ROOT" && python3 -- "$e" --write ) >"$TMP/emit.log" 2>&1
    erc=$?
    if [ "$erc" -ne 0 ]; then
      cannot "the emitter $e exited $erc in write mode: $(tr '\n' ' ' < "$TMP/emit.log" | cut -c1-200)"
      continue
    fi
    note "ran               python3 -- $e --write"
  done < "$TMP/emitters"

  # The emitter's OWN check mode is the second opinion. Without it the only
  # thing verified would be that the emitter did not crash, and an emitter that
  # writes a block it would itself reject is precisely what this catches.
  while IFS= read -r e; do
    [ -n "$e" ] || continue
    ( cd "$ROOT" && python3 -- "$e" ) >"$TMP/check.log" 2>&1
    crc=$?
    if [ "$crc" -ne 0 ]; then
      cannot "after the write, the check mode of $e still exits $crc: $(tr '\n' ' ' < "$TMP/check.log" | cut -c1-200)"
      continue
    fi
    note "verified          python3 -- $e   (its own check mode says 0)"
  done < "$TMP/emitters"
fi

CHANGED=0
while IFS= read -r k; do
  [ -n "$k" ] || continue
  i="${k%% *}"; rel="${k#* }"
  # A line of exactly seven `=` is also a markdown setext underline. Treating
  # one as a surviving conflict marker costs a false rc 2, which is a refusal to
  # act; treating a surviving marker as prose would cost a committed conflict.
  # The cheap mistake is the one worth making.
  grep -q -e '^<<<<<<< ' -e '^>>>>>>> ' -e '^=======$' "$ROOT/$rel"; g=$?
  case "$g" in
    1) : ;;
    0) cannot "$rel: a conflict marker survived the resolution" ;;
    *) cannot "$rel: grep could not read it back (rc $g)" ;;
  esac
  if cmp -s "$TMP/proj.$i" "$ROOT/$rel"; then
    # Byte-identical to the side that was kept: something was "resolved" and
    # nothing was regenerated, so the block still carries one branch's stale
    # figures. A 0 here hands back a tree that looks resolved and says something
    # untrue.
    if [ "$GUARD_NOOP" -eq 1 ]; then
      cannot "$rel: the regeneration was a NO-OP - the file is byte-identical to the side I kept, so the stale figures are still there"
    fi
  else
    CHANGED=$((CHANGED + 1))
    note "regenerated       $rel   (it moved off the side I kept)"
  fi
done < "$TMP/kept"

if [ "$UNMEASURED" -gt 0 ]; then
  printf '\n'
  restore
  verdict 2 "$UNMEASURED failure(s) during the regeneration; the tree is back as I found it"
  exit 2
fi

n_files="$(grep -c . "$TMP/kept")"
n_emit="$(grep -c . "$TMP/emitters")"
verdict 0 "$CHANGED of $n_files file(s) regenerated by $n_emit emitter(s); no conflict marker survived, every check mode green"
exit 0
