name: deploy

on:
  pull_request_target:
    types: [opened, synchronize]

permissions: write-all

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: npm ci && npm run build
      - name: Comment
        run: echo "Preview for ${{ github.event.pull_request.title }}"
